# .github/workflows/ci.yml

# Nome do pipeline exibido no GitHub Actions
name: CI - TaskFlow System

# Define quando o pipeline será executado
on:
  # Executa em pushes na branch main
  push:
    branches:
      - main

  # Executa em pull requests para a branch main
  pull_request:
    branches:
      - main

# Define os jobs do pipeline
jobs:

  # Nome do job principal
  testes:
    
    # Ambiente utilizado pelo GitHub Actions
    runs-on: ubuntu-latest

    steps:

      # Etapa 1 - Faz checkout do código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Etapa 2 - Configura o Python 3.11
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Etapa 3 - Atualiza o pip
      - name: Atualizar pip
        run: |
          python -m pip install --upgrade pip

      # Etapa 4 - Instala dependências do projeto
      - name: Instalar dependências
        run: |
          pip install pytest

      # Etapa 5 - Executa os testes automatizados
      - name: Rodar testes com Pytest
        run: |
          pytest tests/ -v

      # Etapa 6 - Exibe mensagem de sucesso ao final
      - name: Finalização
        run: |
          echo "Pipeline executado com sucesso!"
